name: Deploy Documentation Index

on:
  workflow_run:
    workflows: ['Deploy Documentation (Latest)']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'docs-index'
  cancel-in-progress: true

jobs:
  deploy-index:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Create index.html
        run: |
          mkdir -p temp-index
          cat > temp-index/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>@neofork/devlogr Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  .container {
                      text-align: center;
                      padding: 2rem;
                      background: rgba(255, 255, 255, 0.1);
                      border-radius: 10px;
                      backdrop-filter: blur(10px);
                  }
                  .spinner {
                      border: 4px solid rgba(255, 255, 255, 0.3);
                      border-radius: 50%;
                      border-top: 4px solid white;
                      width: 40px;
                      height: 40px;
                      animation: spin 1s linear infinite;
                      margin: 20px auto;
                  }
                  @keyframes spin {
                      0% { transform: rotate(0deg); }
                      100% { transform: rotate(360deg); }
                  }
                  h1 { margin-bottom: 1rem; }
                  p { opacity: 0.9; }
              </style>
              <script>
                  // Redirect immediately
                  window.location.replace('./latest/');
              </script>
          </head>
          <body>
              <div class="container">
                  <h1>@neofork/devlogr</h1>
                  <div class="spinner"></div>
                  <p>Redirecting to documentation...</p>
                  <p><a href="./latest/" style="color: white;">Click here if not redirected automatically</a></p>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy index to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp-index
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy documentation index.html'
